"""A very small, dependency-free reader for the scorecard PDFs.

The site's ``generate-scorecard.php`` returns a one-page PDF whose *Goaltender
Records* table -- per-goalie, per-period shots and saves -- exists nowhere in
the HTML scoresheet we otherwise collect. We only need the text and where on
the page it sits, not a general PDF renderer, so this extracts exactly that:
the strings drawn by the content stream, each tagged with the position it was
drawn at.

Only the standard library is used, so the Pi needs nothing but ``python3``.

The scorecards are generated by one tool (FPDF), so the content streams are
plain: Flate-compressed, text positioned with ``Tm``/``Td`` and shown with
``Tj``. This handles that shape and does not pretend to be a full parser --
anything it cannot read comes back empty, and the caller treats a scorecard it
cannot read the same as one that was never fetched.
"""

from __future__ import annotations

import re
import zlib
from dataclasses import dataclass

#: A drawn string and where its text object placed the cursor.
@dataclass
class TextItem:
    x: float
    y: float
    text: str


_STREAM = re.compile(rb"stream\r?\n(.*?)\r?\nendstream", re.S)

# Content-stream operators we care about. Text strings are the ( ... ) literals
# shown by Tj/TJ; Tm sets the text matrix outright, Td/TD move relative to the
# line start, BT resets to the origin. Everything else is ignored.
_TOKEN = re.compile(
    r"(?P<tm>[-\d.]+) [-\d.]+ [-\d.]+ [-\d.]+ (?P<tmx>[-\d.]+) (?P<tmy>[-\d.]+) Tm"
    r"|(?P<tdx>[-\d.]+) (?P<tdy>[-\d.]+) T[dD]"
    r"|(?P<bt>BT)"
    r"|\((?P<str>(?:\\.|[^()\\])*)\)"
)

_ESCAPES = {"n": "\n", "r": "\r", "t": "\t", "b": "\b", "f": "\f",
            "(": "(", ")": ")", "\\": "\\"}


def _unescape(raw: str) -> str:
    out, i = [], 0
    while i < len(raw):
        ch = raw[i]
        if ch == "\\" and i + 1 < len(raw):
            nxt = raw[i + 1]
            if nxt in _ESCAPES:
                out.append(_ESCAPES[nxt]); i += 2; continue
            if nxt.isdigit():  # \ddd octal
                m = re.match(r"[0-7]{1,3}", raw[i + 1:])
                if m:
                    out.append(chr(int(m.group(0), 8))); i += 1 + len(m.group(0)); continue
            out.append(nxt); i += 2; continue
        out.append(ch); i += 1
    return "".join(out)


def _inflate_streams(pdf: bytes) -> str:
    """Every Flate stream in the file, decompressed and concatenated.

    Content and object streams are decompressed alike; the ones that are not
    Flate (or not compressed) simply fail to inflate and are skipped, which is
    all we need -- the text we want is in the Flate content stream.
    """
    parts = []
    for match in _STREAM.finditer(pdf):
        body = match.group(1)
        for candidate in (body, body.strip(b"\r\n")):
            try:
                parts.append(zlib.decompress(candidate))
                break
            except zlib.error:
                continue
    return b"\n".join(parts).decode("latin-1")


def text_items(pdf: bytes) -> list[TextItem]:
    """Positioned strings from a scorecard PDF, in draw order.

    Coordinates are in PDF user space (origin bottom-left), so a larger ``y`` is
    higher on the page. Positions are approximate -- good enough to group text
    into visual rows and columns, which is all the table reading needs.
    """
    content = _inflate_streams(pdf)
    items: list[TextItem] = []
    x = y = 0.0
    for m in _TOKEN.finditer(content):
        if m.group("tm") is not None:
            x, y = float(m.group("tmx")), float(m.group("tmy"))
        elif m.group("tdx") is not None:
            x += float(m.group("tdx"))
            y += float(m.group("tdy"))
        elif m.group("bt") is not None:
            x = y = 0.0
        else:
            s = _unescape(m.group("str")).strip()
            if s:
                items.append(TextItem(round(x, 1), round(y, 1), s))
    return items


def rows(items: list[TextItem], tolerance: float = 2.5) -> list[list[TextItem]]:
    """Group items into visual rows by shared ``y``, each sorted left to right.

    Rows come back top of page first. The tolerance absorbs the sub-point
    jitter between cells the generator means to sit on one line.
    """
    buckets: dict[float, list[TextItem]] = {}
    for it in items:
        key = next((k for k in buckets if abs(k - it.y) <= tolerance), it.y)
        buckets.setdefault(key, []).append(it)
    ordered = []
    for key in sorted(buckets, reverse=True):
        ordered.append(sorted(buckets[key], key=lambda t: t.x))
    return ordered
